DROP TABLE BOOK;
DROP TABLE AUTHOR;
DROP TABLE FOO;
DROP TABLE MY_DATES;
DROP TABLE MY_TYPES;
DROP SEQUENCE  "SEQ_FOO";

CREATE TABLE AUTHOR 
( 
  "ID" NUMBER(19) NOT NULL, 
  "NAME" VARCHAR(255), 
  PRIMARY KEY ("ID")
);

CREATE TABLE BOOK 
(
  "ID" NUMBER(19) NOT NULL, 
  "ISBN" VARCHAR(255), 
  "NAME" VARCHAR(255), 
  "AUTHOR_ID" NUMBER(19), 
  PRIMARY KEY ("ID")
);

CREATE TABLE FOO 
(
  ID NUMBER(19) NOT NULL, 
  NAME VARCHAR(50) ,
  PRIMARY KEY ("ID")
);

CREATE TABLE MY_DATES
(
  ID NUMBER(19) NOT NULL, 
  NAME VARCHAR(30) ,
  DURATION_DAY INTERVAL DAY TO SECOND DEFAULT INTERVAL '0' DAY NOT NULL,
  DURATION_YEAR INTERVAL YEAR TO MONTH DEFAULT INTERVAL '0' YEAR NOT NULL,
  INIT DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INIT_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INIT_TSZ TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  INIT_TSL TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE MY_TYPES
( 
  ID NUMBER(19) NOT NULL,
  MY_SMALLINT   NUMBER(8) ,
  MY_INTEGER    NUMBER(14),
  MY_BIGINT     NUMBER(19),
  MY_FLOAT      NUMBER(19,4),
  MY_DECIMAL    NUMBER(19,4),
  MY_VARCHAR    VARCHAR(30) ,
  MY_CHAR       CHAR(10) ,
  MY_BLOB       BLOB,
  MY_CLOB       CLOB,
  MY_DATE       DATE,
  MY_TIMESTAMP  DATE
);

CREATE SEQUENCE  "SEQ_FOO"  MINVALUE 1000 MAXVALUE 9000 INCREMENT BY 1 START WITH 1000 NOCACHE  NOORDER  NOCYCLE ;




--CREATE TABLE MY_SEQUENCES 
--( 
--  "ID" VARCHAR2(32) NOT NULL, 
--  "USED" NUMERIC(1) DEFAULT 0 NOT NULL 
--);
--SELECT * FROM MY_SEQUENCES;
--DELETE FROM MY_SEQUENCES WHERE ID = '505';
--INSERT INTO MY_SEQUENCES (ID,USED) VALUES ('500', 0);
--INSERT INTO MY_SEQUENCES (ID,USED) VALUES ('501', 0);
--INSERT INTO MY_SEQUENCES (ID,USED) VALUES ('502', 0);
--INSERT INTO MY_SEQUENCES (ID,USED) VALUES ('503', 0);
--INSERT INTO MY_SEQUENCES (ID,USED) VALUES ('504', 0);
--INSERT INTO MY_SEQUENCES (ID,USED) VALUES ('505', 0);
