package net.sf.jkniv.sqlegance.builder.xml;

import net.sf.jkniv.sqlegance.KeyGeneratorType;
import net.sf.jkniv.sqlegance.builder.xml.dynamic.ITextTag;

public interface AutoGeneratedKey extends ITextTag
{
    public static final String TAG_NAME           = "autoGeneratedKey";
    public static final String ATTRIBUTE_STRATEGY = "strategy";
    public static final String ATTRIBUTE_COLUMNS  = "columns";
    public static final String ATTRIBUTE_PROPS    = "properties";

    KeyGeneratorType getStrategy();
    
    boolean isAutoStrategy();
    
    boolean isSequenceStrategy();
    
    /**
     * A comma separated list of columns names, when multiple columns are expected
     * @return empty string when haven't value.
     */
    String getColumns();
    
    String[] getColumnsAsArray();
    
    String[] getPropertiesAsArray();
    
    /**
     * A comma separated list of property names, when multiple properties are expected
     * @return empty string when haven't value
     */
    String getProperties();
    
}
