

CREATE JPA_SEQUENCE SEQ_AUTHOR_ID;

CREATE TABLE JPA_AUTHOR
( 
  ID BIGINT NOT NULL, 
  NAME VARCHAR(255), 
  PRIMARY KEY (ID)
);

CREATE TABLE JPA_BOOK
(
  ID BIGINT NOT NULL, 
  ISBN VARCHAR(255), 
  NAME VARCHAR(255), 
  AUTHOR_ID BIGINT, 
  PRIMARY KEY (ID)
);


CREATE TABLE JPA_COLOR
( 
  "ID" BIGINT NOT NULL, 
  "CODE" BIGINT NOT NULL, 
  "NAME" VARCHAR(20),
  "PRIORITY" VARCHAR(20)
);


CREATE TABLE JPA_MY_TYPES
( 
  MY_SMALLINT   SMALLINT NOT NULL,
  MY_INTEGER    INTEGER NOT NULL,
  MY_BIGINT     BIGINT NOT NULL,
  MY_FLOAT      FLOAT NOT NULL,
  MY_DECIMAL    DECIMAL NOT NULL,
  MY_VARCHAR    VARCHAR(30) NOT NULL,
  MY_CHAR       CHAR(10) NOT NULL,
  MY_BLOB       BLOB,
  MY_CLOB       CLOB,
  MY_DATE       DATE NOT NULL,
  MY_TIME       TIME NOT NULL,
  MY_TIMESTAMP  TIMESTAMP NOT NULL
);