DELETE FROM COLOR;

INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('blue', 'HIGH', 100);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('blue', 'NORMAL', 101);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('blue', 'LOW', 102);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('black', 'HIGH', 200);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('black', 'NORMAL', 201);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('black', 'LOW', 202);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('white', 'HIGH', 300);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('white', 'NORMAL', 301);
INSERT INTO COLOR (NAME, PRIORITY, CODE) VALUES ('white', 'LOW', 302);
