/* 
 * JKNIV, whinstone one contract to access your database.
 * 
 * Copyright (C) 2017, the original author or authors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software Foundation, Inc., 
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package net.sf.jkniv.whinstone.jdbc.commands;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import net.sf.jkniv.exception.HandleableException;
import net.sf.jkniv.whinstone.Queryable;
import net.sf.jkniv.whinstone.statement.AutoKey;

/**
 * Call an database sequence and put the value into parameter object from {@link Queryable}
 * 
 * @author Alisson Gomes
 * @since 0.6.0
 */
public class JdbcAutoGeneratedKey implements AutoKey<Long>
{
    private List<Long> keys;
    private final PreparedStatement stmt;
    private final HandleableException handlerException;
    private boolean initated;
    
    public JdbcAutoGeneratedKey(PreparedStatement stmt, HandleableException handlerException)
    {
        this.keys = new ArrayList<Long>();
        this.stmt = stmt;
        this.handlerException = handlerException;
        this.initated = false;
    }
    
    private void generateKeys()
    {
        this.initated = true;
        try
        {
            ResultSet generatedKeys = stmt.getGeneratedKeys();
            while (generatedKeys.next())
            {
                Long id = generatedKeys.getLong(1);
                this.keys.add(id);
            }
        }
        catch (SQLException e)
        {
            handlerException.handle(e);
        }
    }
    
    @Override
    public Long getId()
    {
        if (!initated) generateKeys();
        
        if (isEmpty())
            return null;
                    
        return (Long) this.keys.get(0);
    }
    
    @Override
    public String getUId()
    {
        if (!initated) generateKeys();
        
        if (isEmpty())
            return null;

        return String.valueOf(this.keys.get(0));
    }
    
    @Override
    public Iterator<Long> iterator()
    {
        if (!initated) generateKeys();
        
        return this.keys.iterator();
    }
    
    @Override
    public boolean hasItem()
    {
        if (!initated) generateKeys();
        
        return this.keys.size() > 0;
    }

    @Override
    public boolean isEmpty()
    {
        if (!initated) generateKeys();
        
        return this.keys.isEmpty();
    }

    @Override
    public int size()
    {
        if (!initated) generateKeys();
        
        return this.keys.size();
    }
}
