/* 
 * JKNIV, whinstone one contract to access your database.
 * 
 * Copyright (C) 2017, the original author or authors.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software Foundation, Inc., 
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package net.sf.jkniv.whinstone.jdbc.commands;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import net.sf.jkniv.exception.HandleableException;
import net.sf.jkniv.sqlegance.Insertable;
import net.sf.jkniv.whinstone.Command;
import net.sf.jkniv.whinstone.CommandHandler;
import net.sf.jkniv.whinstone.ConnectionAdapter;
import net.sf.jkniv.whinstone.Queryable;
import net.sf.jkniv.whinstone.jdbc.PreparedStatementStrategy;
import net.sf.jkniv.whinstone.jdbc.params.PreparedStatementAdapterOld;
import net.sf.jkniv.whinstone.params.AutoBindParams;
import net.sf.jkniv.whinstone.params.PrepareParamsFactory;
import net.sf.jkniv.whinstone.params.StatementAdapterOld;

/**
 * 
 * @author Alisson Gomes
 * @since 0.6.0
 */
public class BulkJdbcCommand extends JdbcAbstractCommand
{
    private final Insertable      isql;
    
    public BulkJdbcCommand(Queryable queryable, PreparedStatementStrategy stmtStrategy, Connection conn)
    {
        super(queryable, stmtStrategy, conn);
        this.isql = queryable.getDynamicSql().asInsertable();
    }
    
    @Override
    public <T> T execute()
    {
        Integer affected = 0;
        PreparedStatement stmt = null;
        try
        {
            if (isql.isAutoGenerateKey())
            {
                if (isql.getAutoGeneratedKey().isAutoStrategy())
                {
                    // first execute insert after get keys
                    stmt = prepareStatement();
                    StatementAdapterOld stmtAdapter = new PreparedStatementAdapterOld(stmt);
                    AutoBindParams prepareParams = PrepareParamsFactory.newPrepareParams(stmtAdapter,
                            isql.getParamParser(), queryable);
                    prepareParams.parameterized(queryable.getParamsNames());
                    affected = stmt.executeUpdate();
                    new SettingAutoGeneratedKey(queryable, isql, handlerException).set(stmt);
                }
                else if (isql.getAutoGeneratedKey().isSequenceStrategy())
                {
                    // first get sequence after execute insert
                    new SettingSequenceGeneratedKey(queryable, isql, conn, handlerException).set();
                    stmt = prepareStatement();
                    StatementAdapterOld stmtAdapter = new PreparedStatementAdapterOld(stmt);
                    AutoBindParams prepareParams = PrepareParamsFactory.newPrepareParams(stmtAdapter,
                            isql.getParamParser(), queryable);
                    prepareParams.parameterized(queryable.getParamsNames());
                    affected = stmt.executeUpdate();
                }
            }
            else
            {
                stmt = prepareStatement();
                StatementAdapterOld stmtAdapter = new PreparedStatementAdapterOld(stmt);
                AutoBindParams prepareParams = PrepareParamsFactory.newPrepareParams(stmtAdapter, isql.getParamParser(),
                        queryable);
                prepareParams.parameterized(queryable.getParamsNames());
                affected = stmt.executeUpdate();
            }
        }
        catch (Exception e)
        {
            handlerException.handle(e);
        }
        finally
        {
            close(stmt);
        }
        return (T) affected;
    }
    


}
